{{- if .Values.replicaSet.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: {{ template "mongodb.name" . }}
    chart: {{ template "mongodb.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    deploy: {{ template "datosProyecto.url" . }}
  name: {{ template "mongodb.fullname" . }}-secondary
spec:
  selector:
    matchLabels:
      app: {{ template "mongodb.name" . }}
      release: {{ .Release.Name }}
      component: secondary
  minAvailable: {{ .Values.replicaSet.pdb.minAvailable.secondary }}
{{- end }}
