apiVersion: v1
kind: ConfigMap
metadata:
  name: angular-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    deploy: {{ template "datosProyecto.url" . }}
data:
  config.js: |
        window['httpApiManagerUrl'] = 'https://myprofile.bluespace.eu/backend';
        window['httpBackendUrl'] = '{{ .Values.angular.config.backendUrl }}';
        window['googleApiKey'] = '{{ .Values.angular.config.googleApiKey }}';