apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    deploy: {{ template "datosProyecto.url" . }}
data:
  MONGO_URL: {{ template "mongodb_replicaset_url" . }}
  ENV: DEV
  MONGO_HOST: {{ template "mongodb_replicaset_host" . }}
  DatabaseName: {{ .Values.mongodb.database }}
  GatewayUrl: {{ .Values.backend.config.gateway }}
  InviteConfirmation: {{ .Values.backend.config.inviteUrl }}
  ProfileAPI: {{ .Values.backend.config.profileApi }}
  ContractsAPI: {{ .Values.backend.config.contractsApi }}
  CountriesAPI:  {{ .Values.backend.config.countriesApi }}
  StoresAPI:  {{ .Values.backend.config.storesApi }}
  AccountsAPI:  {{ .Values.backend.config.accountsApi }}
  MailFrom: {{ .Values.backend.config.mailFrom }}
  Email__Smtp__Host: {{ .Values.backend.config.mailHost }}
  Identity__BaseUri: {{ .Values.identity.baseuri }}
  Identity__Endpoints__Authorize: {{ .Values.identity.endpoints.authorize }}
  Identity__Endpoints__Validate: {{ .Values.identity.endpoints.validate }}
  Identity__Endpoints__Provisioning: {{ .Values.identity.endpoints.provisioning }}
  FormContactEmail: {{ .Values.backend.config.contactMail }}
  GatewaySmUrl: {{ .Values.backend.config.sm.gateway }}
  ContractsBySMCodeAPI: {{ .Values.backend.config.sm.contractsCodeApi }}
  UnitsAPI: {{ .Values.backend.config.unitsApi }}
  ContractSMAPI: {{ .Values.backend.config.sm.contractsApi }}
  GatewaySignatureUrl: {{ .Values.backend.config.sign.gateway }}
  SignatureEndpoint: {{ .Values.backend.config.sign.endpoint }}
  GatewayDocumentUrl: {{ .Values.backend.config.docs.gateway }}
  DocumentsAPI:  {{ .Values.backend.config.docs.documentsApi }}
