apiVersion: v1
kind: ConfigMap
metadata:
  name: docapi-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    deploy: {{ template "datosProyecto.url" . }}
data:
  DatabaseName: {{ .Values.docapi.config.database }}
  ServiceUrl: {{ .Values.docapi.config.serviceUrl }}
  SitesUrl: {{ .Values.docapi.config.sitesUrl }}
  API: {{ .Values.docapi.config.api }}