apiVersion: v1
kind: Service
metadata:
  name: docapi-service{{ template "include_branch_name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: docapi
    deploy: {{ template "datosProyecto.url" . }}
spec:
  ports:
    - name : tcp 
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: docapi{{ template "include_branch_name" . }}