apiVersion: v1
kind: ConfigMap
metadata:
  name: angular-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    deploy: {{ template "datosProyecto.url" . }}
data:
  config.js: |
        window['httpApiManagerUrl'] = 'https://myprofile-pre.bluespace.eu/backend';
        window['httpBackendUrl'] = 'https://myprofile-pre.bluespace.eu/backend';
        window['googleApiKey'] = 'AIzaSyDhc6D7txBsiVTTgWFiflBtvrAycaw9l1w';