apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: backend-deployment{{ template "include_branch_name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: backend{{ template "include_branch_name" . }}
    deploy: {{ template "datosProyecto.url" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend{{ template "include_branch_name" . }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend{{ template "include_branch_name" . }}
    spec:
      initContainers:
      - name: wait-db-readyness
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup {{ template "mongodb_replicaset_host" . }}; do echo waiting for {{ template "mongodb_replicaset_host" . }}; sleep 2; done;']
        imagePullPolicy: Always
      containers:
      - image: "{{ .Values.backend.registry }}/{{ .Values.backend.repository }}:{{ .Values.backend.tag }}"
        name: backend{{ template "include_branch_name" . }}
        env:
          - name: MONGO_URL
            value: {{ template "mongodb_replicaset_url" . }}
          - name: ENV
            value: DEV
          - name: MONGO_HOST
            value: {{ template "mongodb_replicaset_host" . }}
          - name: MONGO_DATABASE
            value: customerportal
          - name: GatewayUrl
            value: http://crmapi-service
          - name: INVITE_URL
            value: https://myprofile-pre.bluespace.eu/signup/
          - name: ProfileAPI
            value: /crmapi/Contacts/
          - name: ContractsAPI
            value: /crmapi/Contracts/
          - name: MailFrom
            value: no-reply@bluespace.eu
          - name: Email__Smtp__Host
            value: smtp.office365.com
          - name: Email__Smtp__Username
            value: no-reply@bluespace.eu
          - name: Email__Smtp__Password
            value: EoE4RygWaKVvQrvVu7dp
        ports:
        - containerPort: 80
          name: http
        imagePullPolicy: Always
      imagePullSecrets:
        - name: quantion-registry
      