angular:
  registry: registry.quantion.com
  replicas: 1
  repository: bluespace-customerportal-web/frontend
  config:
    backendUrl: https://bluespace-customerportal-web-dev.quantion.com/backend
    googleApiKey: AIzaSyDhc6D7txBsiVTTgWFiflBtvrAycaw9l1w
  tag: v_1.2

backend:
  registry: registry.quantion.com
  replicas: 1
  repository: bluespace-customerportal-web/backend
  tag: v_1.2
  config:
    gateway: http://crmapi-service
    inviteUrl: https://bluespace-customerportal-web-dev.quantion.com/signup/
    profileApi: /crmapi/Contacts/
    contractsApi: /crmapi/Contracts/
    accountsApi: /crmapi/Accounts/
    countriesApi: /crmapi/Countries/
    storesApi: /crmapi/Sites/
    unitsApi;: /crmapi/Units/
    mailFrom: no-reply@bluespace.eu
    mailHost: smtp.office365.com
    contactMail: samuel.sole@quantion.com
    sm:
      gateway: http://smapi-service
      contractsCodeApi: /crmapi/contracts/code/
      contractsApi: /smapi/Contract/
    sign:
      gateway: http://signaturitapi-service
      endpoint: /api/signature/
    docs:
      gateway: http://sharepointapi-service
      documentsApi: /api/documents/

identity:
  baseuri: https://identity-pre.bluespace.eu
  endpoints:
    authorize: oauth2/token
    validate: oauth2/introspect
    provisioning: wso2/scim/Users
    groups: scim2/Grooups
    revoke: oauth2/revoke

ingress:
  secretName: quantion-tls

crmapi:
  registry: registry.quantion.com
  replicas: 1
  repository: bluespace-customerportal-web/crmapi
  tag: v_1.2
  config:
    serviceUrl: http://93.90.28.112/BLUESPACEPRE/
    domain: BLUESPACE
    api: api/data/v8.1/

smapi:
  registry: registry.quantion.com
  replicas: 1
  repository: bluespace-customerportal-web/smapi
  tag: dev
  config:
    odbcConnection: Driver=SQL Anywhere 16;UID=BIuser;PWD=RADicalREAD**;Host=93.90.28.125;Port=2638;Servername=RADTEST98SQL;Database=RADTEST98

signaturitapi:
  registry: registry.quantion.com
  replicas: 1
  repository: bluespace-customerportal-web/signaturitapi
  tag: v_1.2
  config:
    signaturitapi: https://api.sandbox.signaturit.com/v3/
    token: capuPuPiidZlIyaCggnQfUpulsznuFJBHOoaJYPsNmGzcxKmBBfOMpjZagnNgUlSqPqgZdBsSqTdMeBToaLOVn
    database: signatures
    eventsUrl: https://bluespace-customerportal-web-dev.quantion.com/signature/api/events
    gatewayUrl: http://sharepointapi-service
    gatewayUrlPortal: http://backend-service
    documentationApi: api/Document
    NotificationApi: api/events

datosProyecto:
  aplicacion: web
  cliente: bluespace
  entorno: dev
  proyecto: customerportal
  whitelist:
    enabled: false
    listIp:
    - 2.139.194.97/32

mongodb:
  database: customerportal
  datosProyecto:
    aplicacion: web
    cliente: bluespace
    entorno: dev
    proyecto: customerportal
  enabled: true
  fullnameOverride: mongodb
  persistence:
    enabled: true
    size: 1Gi
  replicaSet:
    enabled: false
    name: rs0
    pdb:
      enabled: false
      minAvailable:
        arbiter: 1
        primary: 1
        secondary: 1
    replicas:
      arbiter: 1
      secondary: 2
  usePassword: false
