apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-mongodb-primary-0
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 128Gi
  selector:
    matchLabels:
      purpose: mongodb-customerportal