apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-customerportal-pv
  labels: 
    purpose: mongodb-customerportal
spec:
  capacity:
    storage: 128Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  azureDisk:
    kind: Managed
    diskName: mongodb-customerportal-pro
    diskURI: /subscriptions/83df56fa-0451-4d73-bffd-280158bd1d72/resourcegroups/MC_kubernetes_bluespace_francecentral/providers/Microsoft.Compute/disks/mongodb-customerportal-pro
