apiVersion: v1
kind: Service
metadata:
  name: backend-service{{ template "include_branch_name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: backend
    deploy: {{ template "datosProyecto.url" . }}
spec:
  ports:
    - name : tcp 
      port: 80
      targetPort: 80
      protocol: TCP
    - name : https 
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: backend{{ template "include_branch_name" . }}
