angular:
  registry: registry.quantion.com
  replicas: 1
  repository: bluespace-customerportal-web/frontend
  config:
    backendUrl: https://myprofile.bluespace.eu/backend
    googleApiKey: AIzaSyDhc6D7txBsiVTTgWFiflBtvrAycaw9l1w
  tag: mvp

backend:
  registry: registry.quantion.com
  replicas: 1
  repository: bluespace-customerportal-web/backend
  tag: mvp
  config:
    gateway: http://crmapi-service
    inviteUrl: https://myprofile.bluespace.eu/signup/
    profileApi: /crmapi/Contacts/
    contractsApi: /crmapi/Contracts/
    accountsApi: /crmapi/Accounts/
    countriesApi: /crmapi/Countries/
    storesApi: /crmapi/Sites/
    mailFrom: no-reply@bluespace.eu
    mailHost: smtp.office365.com
    contactMail: samuel.sole@quantion.com

identity:
  baseuri: https://identity.bluespace.eu
  endpoints:
    authorize: oauth2/token
    validate: oauth2/introspect
    provisioning: wso2/scim/Users

ingress:
  secretName: bluespace-tls

crmapi:
  registry: registry.quantion.com
  replicas: 1
  repository: bluespace-customerportal-web/crmapi
  tag: mvp
  config:
    serviceUrl: http://93.90.28.112/BLUESPACEPRE/
    domain: BLUESPACE
    api: api/data/v8.1/

datosProyecto:
  aplicacion: web
  cliente: bluespace
  entorno: dev
  proyecto: customerportal
  whitelist:
    enabled: false
    listIp:
    - 2.139.194.97/32
    
mongodb:
  database: customerportal
  datosProyecto:
    aplicacion: web
    cliente: bluespace
    entorno: dev
    proyecto: customerportal
  enabled: true
  fullnameOverride: mongodb
  persistence:
    enabled: true
    size: 1Gi
  replicaSet:
    enabled: false
    name: rs0
    pdb:
      enabled: false
      minAvailable:
        arbiter: 1
        primary: 1
        secondary: 1
    replicas:
      arbiter: 1
      secondary: 2
  usePassword: false
