angular:
  registry: bluespaceregistry.azurecr.io
  replicas: 1
  repository: bluespace-customerportal-web/frontend
  config:
    backendUrl: https://myprofile.bluespace.eu/backend
    googleApiKey: AIzaSyDhc6D7txBsiVTTgWFiflBtvrAycaw9l1w
    googleAnalyticsId: UA-160385611-1
  tag: v_1.5

backend:
  registry: bluespaceregistry.azurecr.io
  replicas: 1
  repository: bluespace-customerportal-web/backend
  tag: v_1.5
  config:
    inviteUrl: https://myprofile.bluespace.eu/signup/
    resetPasswordUrl: https://myprofile-pre.bluespace.eu/reset-password/
    mailFrom: no-reply@bluespace.eu
    mailHost: smtp.office365.com
    contactMail: chema.gonzalez@bluespace.es
    storesMail: jordi.piella@quantion.com
    signatureEventsUrl: http://backend-service/api/Events
    precognisPaymentsUrl: https://bluespacetest.precognis.com/openbravo/wspr/
    precognisChangePaymentMethod: com.precognis.einapay.bluespace.webportalcard/changepaymentmethod
    precognisCardConfirmationToken: com.precognis.einapay.bluespace.cardsignature/changepaymentmethod
    changePaymentMethodCardResponse: http://myprofile.bluespace.eu/backend/api/payment/changepaymentmethod/card/response
    environment: PRO
    crm:
      gateway: http://crmapi-service
      profileApi: /crmapi/Contacts/
      contractsApi: /crmapi/Contracts/
      accountsApi: /crmapi/Accounts/
      countriesApi: /crmapi/Countries/
      storesApi: /crmapi/Sites/
      unitsApi: /crmapi/Units/
      contractsCodeApi: /crmapi/Contracts/code/
    sm:
      gateway: http://smapi-service
      contractsApi: /smapi/Contract/
      accountApi: /smapi/Account/
      invoiceApi: /smapi/Invoice/
    sign:
      gateway: http://signaturitapi-service
      endpoint: api/signature/
    docs:
      gateway: http://docapi-service/
      documentsApi: api/Documents/
      searchEndpoint: api/Documents/Search/

identity:
  baseuri: https://identity.bluespace.eu
  endpoints:
    authorize: oauth2/token
    validate: oauth2/introspect
    provisioning: wso2/scim/Users
    groups: scim2/Groups
    revoke: oauth2/revoke

ingress:
  secretName: bluespace-tls

crmapi:
  registry: bluespaceregistry.azurecr.io
  replicas: 1
  repository: bluespace-customerportal-web/crmapi
  tag: v_1.5
  config:
    serviceUrl: http://93.90.28.112/BLUESPACEPRE/
    domain: BLUESPACE
    api: api/data/v8.1/

smapi:
  registry: bluespaceregistry.azurecr.io
  replicas: 1
  repository: bluespace-customerportal-web/smapi
  tag: v_1.5
  config:
    odbcConnection: Driver=SQL Anywhere 16;UID=BIuser;PWD=RADicalREAD**;Host=93.90.28.125;Port=2638;Servername=RADTEST98SQL;Database=RADTEST98

signaturitapi:
  registry: bluespaceregistry.azurecr.io
  replicas: 1
  repository: bluespace-customerportal-web/signaturitapi
  tag: v_1.5
  config:
    signaturitapi: https://api.signaturit.com/v3/
    token: clItRnRdObkXobAYlIqZKBIwWQSEkKXscpDXLhloqISMtUpzKrktvOnquzauTxNFdweLYFKqiYkLicuoMNKawW
    database: signatures
    eventsUrl: https://myprofile.bluespace.eu/signature/api/Events
    gatewayUrl: http://docapi-service/
    documentationApi: api/Documents
    documentationAuditApi: api/Documents/Audit

docapi:
  registry: bluespaceregistry.azurecr.io
  replicas: 1
  repository: bluespace-customerportal-web/sharepointapi
  tag: v_1.5
  config:
    database: documents
    serviceUrl: https://bluespaceselfstorage.sharepoint.com
    sitesUrl: /sites/Stores/
    api: _api/
    environment: PRO
    siteName: SantBoi
    sharedDocumentFolder: Documentos compartidos


datosProyecto:
  aplicacion: web
  cliente: bluespace
  entorno: pro
  proyecto: customerportal
  whitelist:
    enabled: false
    listIp:
    - 2.139.194.97/32
    
mongodb:
  database: customerportal
  datosProyecto:
    aplicacion: web
    cliente: bluespace
    entorno: pro
    proyecto: customerportal
  enabled: true
  fullnameOverride: mongodb
  persistence:
    enabled: true
    size: 128Gi
  replicaSet:
    enabled: true
    name: rs0
    pdb:
      enabled: false
      minAvailable:
        arbiter: 1
        primary: 1
        secondary: 1
    replicas:
      arbiter: 1
      secondary: 2
  usePassword: false
