apiVersion: v1
kind: ConfigMap
metadata:
  name: angular-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    deploy: {{ template "datosProyecto.url" . }}
data:
  config.js: |
        window['httpApiManagerUrl'] = 'https://myprofile-pre.bluespace.eu/backend';
        window['httpBackendUrl'] = '{{ .Values.angular.config.backendUrl }}';
        window['googleApiKey'] = '{{ .Values.angular.config.googleApiKey }}';
        window['googleAnalyticsId'] = '{{ .Values.angular.config.googleAnalyticsId }}';
        window['blobStorageUnitContainer'] = '{{ .Values.angular.config.blobStorageUnitContainer }}';
        window['httpBlobStorageUrl'] = '{{ .Values.angular.config.httpBlobStorageUrl }}';
        window['unitCategoryImage'] = '{{ .Values.angular.config.unitCategoryImage }}';