apiVersion: v1
kind: ConfigMap
metadata:
  name: crmapi-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    deploy: {{ template "datosProyecto.url" . }}
data:
  ServiceUrl: {{ .Values.crmapi.config.serviceUrl }}