apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: docapi-deployment{{ template "include_branch_name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: docapi{{ template "include_branch_name" . }}
    deploy: {{ template "datosProyecto.url" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docapi{{ template "include_branch_name" . }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: docapi{{ template "include_branch_name" . }}
      annotations:
        checksum/config: {{include (print $.Template.BasePath "/docapi-configmap.yaml") .| sha256sum }}
    spec:
      containers:
      - image: "{{ .Values.docapi.registry }}/{{ .Values.docapi.repository }}:{{ .Values.docapi.tag }}"
        name: docapi{{ template "include_branch_name" . }}
        env:
          - name: ClientId
            valueFrom:
              secretKeyRef:
                name: sharepoint-credentials
                key: clientId
          - name: ClientSecret
            valueFrom:
              secretKeyRef:
                name: sharepoint-credentials
                key: clientSecret
          - name: TenantId
            valueFrom:
              secretKeyRef:
                name: sharepoint-credentials
                key: tenantId
          - name: Realm
            valueFrom:
              secretKeyRef:
                name: sharepoint-credentials
                key: realm
        envFrom:
          - configMapRef:
              name: docapi-configmap
        ports:
        - containerPort: 80
          name: http
        imagePullPolicy: Always
      imagePullSecrets:
        - name: quantion-registry