apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-customerportal-pre-pv
  labels: 
    purpose: mongodb-customerportal-pre
spec:
  capacity:
    storage: 1Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  azureDisk:
    kind: Managed
    diskName: mongodb-customerportal-pre
    diskURI: /subscriptions/83df56fa-0451-4d73-bffd-280158bd1d72/resourceGroups/MC_kubernetes_bluespace_francecentral/providers/Microsoft.Compute/disks/mongodb-customerportal-pre
