{
  "kind": "Secret",
  "apiVersion": "v1",
  "metadata": {
    "name": "customerportal-credentials",
    "namespace": "bluespace",
    "selfLink": "/api/v1/namespaces/bluespace/secrets/customerportal-credentials",
    "uid": "9c90f5b8-d161-4146-87ac-79da302e93db",
    "resourceVersion": "10141119",
    "creationTimestamp": "2020-02-06T10:00:58Z"
  },
  "data": {
    "apikey": "RjU2QTJFNjEtNkQzQy00QzNGLUIxQjUtMTZDMzM1RUFEQTk2"
  },
  "type": "Opaque"
}