apiVersion: v1
kind: ConfigMap
metadata:
  name: crmapi-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    deploy: {{ template "datosProyecto.url" . }}
data:
  ServiceUrl: {{ .Values.crmapi.config.serviceUrl }}
  ConnectionStrings__serverdb: {{ .Values.mongodb.url }}
  DatabaseName: {{ .Values.mongodb.database }}
  Logging__LogLevel__Default: {{ .Values.datosProyecto.logLevel}}
  Logging__Serilog__LogLevel__Default: {{ .Values.datosProyecto.mongologLevel}}
  Authorization: {{ .Values.crmapi.config.authorization }}
  Environment: {{ .Values.crmapi.config.environment }}