apiVersion: v1
kind: ConfigMap
metadata:
  name: docapi-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    deploy: {{ template "datosProyecto.url" . }}
data:
  MONGO_URL: {{ template "mongodb_replicaset_url" . }}
  DatabaseName: {{ .Values.docapi.config.database }}
  ServiceUrl: {{ .Values.docapi.config.serviceUrl }}
  SitesUrl: {{ .Values.docapi.config.sitesUrl }}
  API: {{ .Values.docapi.config.api }}
  ConnectionStrings__serverdb: {{ template "mongodb_replicaset_url" . }}
  Environment: {{ .Values.docapi.config.environment }}
  SharedDocumentsFolder: {{ .Values.docapi.config.sharedDocumentFolder }}
  SiteNameSharepoint: {{ .Values.docapi.config.siteName }}
  GatewayContractsUrl: {{ .Values.docapi.config.gatewayUrl }}
  ContractsAPI: {{ .Values.docapi.config.contractsApi }}
  SitesAPI: {{ .Values.docapi.config.sitesApi }}
  Logging__LogLevel__Default: {{ .Values.datosProyecto.logLevel}}
  Logging__Serilog__LogLevel__Default: {{ .Values.datosProyecto.mongologLevel}}
  AzureBlobStorageConnectionString: {{ .Values.docapi.config.azureBlobStorageConnectionString }}
  EmailITSupport: {{ .Values.docapi.config.emailITSupport }}
  Email__Smtp__Host: {{ .Values.backend.config.mailHost }}
  MailFrom: {{ .Values.backend.config.mailFrom }}