apiVersion: v1
kind: ConfigMap
metadata:
  name: smapi-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    deploy: {{ template "datosProyecto.url" . }}
data:
  OdbcConnection: {{ .Values.smapi.config.odbcConnection }}