apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: smapi-deployment{{ template "include_branch_name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: smapi{{ template "include_branch_name" . }}
    deploy: {{ template "datosProyecto.url" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smapi{{ template "include_branch_name" . }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: smapi{{ template "include_branch_name" . }}
      annotations:
        checksum/config: {{include (print $.Template.BasePath "/smapi-configmap.yaml") .| sha256sum }}
    spec:
      containers:
      - image: "{{ .Values.smapi.registry }}/{{ .Values.smapi.repository }}:{{ .Values.smapi.tag }}"
        name: smapi{{ template "include_branch_name" . }}
        envFrom:
          - configMapRef:
              name: smapi-configmap
        ports:
        - containerPort: 80
          name: http
        imagePullPolicy: Always
      imagePullSecrets:
        - name: bluespace-registry
      
        