
kind: Secret
apiVersion: v1
type: Opaque
metadata: 
  name: identity-credentials
  namespace: myprofile-pre
data: 
  clientId: ajRlbjZaT2k2MHVIMjFWbEpEOHZ6cGZwMlJBYQ==
  clientSecret: STVQZE12bDlUTEVZNVE1c3hOTkljeFl1dGZBYQ==
  password: QjF1M3NwNGMz
  user: YWRtaW5ibHVlc3BhY2U=
