apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-wso2-apim-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels: 
      app: mysql-wso2-apim-pre