angular:
  registry: bluespaceregistry.azurecr.io
  replicas: 1
  repository: bluespace-customerportal-web/frontend
  config:
    backendUrl: https://myprofile-pre.bluespace.eu/backend
    googleApiKey: AIzaSyDhc6D7txBsiVTTgWFiflBtvrAycaw9l1w
    googleAnalyticsId: UA-160385611-1
  tag: v_1.9

backend:
  registry: bluespaceregistry.azurecr.io
  replicas: 1
  repository: bluespace-customerportal-web/backend
  tag: v_1.9
  config:
    inviteUrl: https://myprofile-pre.bluespace.eu/signup/
    resetPasswordUrl: https://myprofile-pre.bluespace.eu/reset-password/
    mailFrom: no-reply@bluespace.eu
    mailHost: smtp.office365.com
    contactMail: samuel.sole@quantion.com
    storesMail: jordi.piella@quantion.com
    signatureEventsUrl: http://backend-service/api/Events
    precognisPaymentsUrl: https://bluespacetest.precognis.com/openbravo/wspr/
    changePaymentMethodCardResponse: https://myprofile-pre.bluespace.eu/backend/api/payment/changepaymentmethod/card/response
    payInvoiceByNewCardMethodCardResponse: https://myprofile-pre.bluespace.eu/backend/api/payment/invoice/response
    precognis:
      PaymentsUrl: https://bluespacetest.precognis.com/openbravo/wspr/
      ChangePaymentMethod: com.precognis.einapay.bluespace.webportalcard/changepaymentmethod
      CardConfirmationToken: com.precognis.einapay.bluespace.cardsignature/changepaymentmethod
      PayInvoice: com.precognis.einapay.bluespace.payinvoice_sm/usetoken
      GetCardEndpoint: com.precognis.einapay.bluespace.checkcard
      PayInvoiceNewCard: com.precognis.einapay.bluespace.payinvoice_sm/usenewcard
    environment: PRE
    crm:
      gateway: http://crmapi-service
      profileApi: /crmapi/Contacts/
      contractsApi: /crmapi/Contracts/
      accountsApi: /crmapi/Accounts/
      countriesApi: /crmapi/Countries/
      storesApi: /crmapi/Sites/
      unitsApi: /crmapi/Units/
      contractsCodeApi: /crmapi/Contracts/code/
      paymentsApi: /crmapi/Payments/
    sm:
      gateway: http://smapi-service
      contractsApi: /smapi/Contract/
      accountApi: /smapi/Account/
      invoiceApi: /smapi/Invoice/
      invoicePaymentApi: /smapi/Invoice/payment/
    sign:
      gateway: http://signaturitapi-service
      endpoint: api/signature/
    docs:
      gateway: http://docapi-service/
      documentsApi: api/Documents/
      searchEndpoint: api/Documents/Search/

identity:
  baseuri: https://identity-pre.bluespace.eu
  endpoints:
    authorize: oauth2/token
    validate: oauth2/introspect
    provisioning: wso2/scim/Users
    groups: scim2/Groups
    revoke: oauth2/revoke

ingress:
  secretName: bluespace-tls

crmapi:
  registry: bluespaceregistry.azurecr.io
  replicas: 1
  repository: bluespace-customerportal-web/crmapi
  tag: v_1.9
  config:
    serviceUrl: http://93.90.28.112/BLUESPACEPRE/
    domain: BLUESPACE
    api: api/data/v8.1/

smapi:
  registry: bluespaceregistry.azurecr.io
  replicas: 1
  repository: bluespace-customerportal-web/smapi
  tag: v_1.9
  config:
    odbcConnection: Driver=SQL Anywhere 16;UID=BIuser;PWD=RADicalREAD**;Host=93.90.28.125;Port=2638;Servername=RADTEST98SQL;Database=RADTEST98

signaturitapi:
  registry: bluespaceregistry.azurecr.io
  replicas: 1
  repository: bluespace-customerportal-web/signaturitapi
  tag: v_1.9
  config:
    signaturitapi: https://api.sandbox.signaturit.com/v3/
    token: capuPuPiidZlIyaCggnQfUpulsznuFJBHOoaJYPsNmGzcxKmBBfOMpjZagnNgUlSqPqgZdBsSqTdMeBToaLOVn
    database: signatures
    eventsUrl: https://myprofile-pre.bluespace.eu/signature/api/Events
    gatewayUrl: http://docapi-service/
    documentationApi: api/Documents
    documentationAuditApi: api/Documents/Audit

docapi:
  registry: bluespaceregistry.azurecr.io
  replicas: 1
  repository: bluespace-customerportal-web/sharepointapi
  tag: v_1.9
  config:
    database: documents
    serviceUrl: https://bluespaceselfstorage.sharepoint.com
    sitesUrl: /sites/Stores-PRE/
    api: _api/
    environment: PRE
    siteName: SantBoi
    sharedDocumentFolder: Documentos compartidos
    gatewayUrl: http://crmapi-service
    contractsApi: /crmapi/Contracts/
    sitesApi: /crmapi/Sites/

datosProyecto:
  aplicacion: web
  cliente: bluespace
  entorno: pre
  proyecto: customerportal
  whitelist:
    enabled: false
    listIp:
    - 2.139.194.97/32
    
mongodb:
  database: customerportal
  datosProyecto:
    aplicacion: web
    cliente: bluespace
    entorno: dev
    proyecto: customerportal
  enabled: true
  fullnameOverride: mongodb
  persistence:
    enabled: true
    existingClaim: "mongodb-customerportal-pre-pvc"
    size: 1Gi
  replicaSet:
    enabled: false
    name: rs0
    pdb:
      enabled: false
      minAvailable:
        arbiter: 1
        primary: 1
        secondary: 1
    replicas:
      arbiter: 1
      secondary: 2
  usePassword: false
