apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-customerportal-pre-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      purpose: mongodb-customerportal-pre
